const Head = () => {
  return (
    <>
      <title>The Present Future Dashboard | World Summit 2023</title>
      <meta content="width=device-width, initial-scale=1" user-scalable="no" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}

export default Head;
